version: '3.1'

services:
  app:
    image: mmustapha/simple-crud:1.0 # ENSURE TO UPDATE THE TAG
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      - PUBLIC_HOST=${PUBLIC_HOST}
      - PSQL_URL=${PSQL_URL}

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080